---
title: "tables"
author: "Marie Moriarty"
date: "`r Sys.Date()`"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r mageck}
# Import MAGeCK data set
library(readr)
library(ggplot2)

mageck <- read_delim("mageckRRA.gene_summary.txt", 
    delim = "\t", escape_double = FALSE, 
    trim_ws = TRUE)

# Reassign column names
colnames(mageck) <- c("id",
                      "num",
                      "neg.score",
                      "neg.p_value",
                      "neg.fdr",
                      "neg.rank",
                      "neg.goodsgrna",
                      "neg.lfc",
                      "pos.score",
                      "pos.p_value",
                      "pos.fdr",
                      "pos.rank",
                      "pos.goodsgrna",
                      "lfc"
                      )

# Convert goodsgrna to factor
mageck$num <- as.factor(mageck$num)
mageck$neg.goodsgrna <- as.factor(mageck$neg.goodsgrna)
mageck$pos.goodsgrna <- as.factor(mageck$pos.goodsgrna)

# Delete neg.lfc
mageck <- mageck[,-8]

selection <- NULL

# Sort values based on p-values to see which selection p-value is lower
for (i in 1:length(mageck$id)){
  if (mageck$neg.p_value[i] > mageck$pos.p_value[i]){
    selection[i] <- "positive"
  } else {       
    selection[i] <- "negative"
  } 
}

# Append to mageck data frame as factor
mageck$selection <- as.factor(selection)
summary(mageck$selection)

# view data summary
summary(mageck)

```

```{r}
knitr::kable(mageck[1:5,])
```
